### ISSUE TITLE
Question: SQLite

### ISSUE THREAD

**Issue by centuryx476** [alfredosa/devtime.nvim#1]
This is exactly what I have been looking for. I've always wanted to know how long I work on projects or files. I see there is WakaTime but that requires an account to be made and it goes to their cloud. No no not for me. I like local

Question: As of now in order to get the data out I just query the sqlite table ?

**Comment by alfredosa** [comment]
Hey!! I'm really happy to hear this, I agree that I also don't like the idea of having to share my data also (we already worry to much about that nowadays lol). This is the way.

Yes that's right, but actually today I was thinking that maybe adding some queries to neovim would be really cool!! I just cooked the pr, but here is a screenshot: 

![Uploading Screenshot 2024-11-18 at 19.24.20.png…]()

Otherwise you can use the queries as an example.

I also fixed a bug today where neovim was pushing some random fileype of nil (telescope buffers or neotree are a good example). Will push the pr today :)

**Comment by alfredosa** [comment]
<img width="1790" alt="Screenshot 2024-11-18 at 19 24 20" src="https://github.com/user-attachments/assets/87fe8b37-cee6-4eba-ace6-9f6db903925f">
Img broken in past comment

**Comment by centuryx476** [comment]
Great,
I noticed those nil values and filtered them out. 
I' am writing a script that takes the .db file and is going to fill an MS SQL database with this information. Then I can really have fun with the data...

Thank you again!!

Love this plugin....
